Resync libopencm3

diff --git a/src/libopencm3/Makefile b/src/libopencm3/Makefile
--- a/src/libopencm3/Makefile
+++ b/src/libopencm3/Makefile
@@ -20,19 +20,22 @@
 PREFIX		?= arm-none-eabi
 #PREFIX		?= arm-elf
 
-ifeq ($(DETECT_TOOLCHAIN),)
+STYLECHECK      := scripts/checkpatch.pl
+STYLECHECKFLAGS := --no-tree -f --terse --mailback
+
 DESTDIR		?= /usr/local
-else
-DESTDIR		?= $(shell dirname $(shell readlink -f $(shell which $(PREFIX)-gcc)))/..
-endif
 
-INCDIR		= $(DESTDIR)/$(PREFIX)/include
-LIBDIR		= $(DESTDIR)/$(PREFIX)/lib
-SHAREDIR	= $(DESTDIR)/$(PREFIX)/share/libopencm3/scripts
-INSTALL		= install
+INCDIR		:= $(DESTDIR)/$(PREFIX)/include
+LIBDIR		:= $(DESTDIR)/$(PREFIX)/lib
+SHAREDIR	:= $(DESTDIR)/$(PREFIX)/share/libopencm3/scripts
+INSTALL		:= install
 
-SRCLIBDIR = $(shell pwd)/lib
-TARGETS = stm32/f1 stm32/f2 stm32/f4 stm32/l1 lpc13xx lpc17xx lpc43xx lm3s  efm32/efm32tg efm32/efm32g efm32/efm32lg efm32/efm32gg
+SRCLIBDIR:= $(realpath lib)
+
+TARGETS:= stm32/f0 stm32/f1 stm32/f2 stm32/f3 stm32/f4 stm32/l1 lpc13xx lpc17xx \
+	  lpc43xx/m4 lpc43xx/m0 lm3s lm4f \
+	  efm32/efm32tg efm32/efm32g efm32/efm32lg efm32/efm32gg \
+	  sam/3a sam/3n sam/3s sam/3u sam/3x
 
 # Be silent per default, but 'make V=1' will show all compiler calls.
 ifneq ($(V),1)
@@ -41,36 +44,27 @@ Q := @
 MAKEFLAGS += --no-print-directory
 endif
 
+IRQ_DEFN_FILES	:= $(shell find . -name 'irq.json')
+STYLECHECKFILES := $(shell find . -name '*.[ch]')
+
 all: build
 
-build: lib examples
+build: lib
 
-generatedheaders:
-	@printf "  UPDATING HEADERS\n"
-	$(Q)for yamlfile in `find . -name 'irq.yaml'`; do \
-		./scripts/irq2nvic_h $$yamlfile ; \
-	done
+%.genhdr:
+	@printf "  GENHDR  $*\n";
+	@./scripts/irq2nvic_h ./$*;
 
-cleanheaders:
-	@printf "  CLEANING HEADERS\n"
-	$(Q)for yamlfile in `find . -name 'irq.yaml'`; do \
-		./scripts/irq2nvic_h --remove $$yamlfile ; \
-	done
+%.cleanhdr:
+	@printf "  CLNHDR  $*\n";
+	@./scripts/irq2nvic_h --remove ./$*
 
 LIB_DIRS:=$(wildcard $(addprefix lib/,$(TARGETS)))
-$(LIB_DIRS): generatedheaders
+$(LIB_DIRS): $(IRQ_DEFN_FILES:=.genhdr)
 	@printf "  BUILD   $@\n";
 	$(Q)$(MAKE) --directory=$@ SRCLIBDIR=$(SRCLIBDIR)
 
 lib: $(LIB_DIRS)
-	$(Q)true
-
-EXAMPLE_DIRS:=$(sort $(dir $(wildcard $(addsuffix /*/*/Makefile,$(addprefix examples/,$(TARGETS))))))
-$(EXAMPLE_DIRS): lib
-	@printf "  BUILD   $@\n";
-	$(Q)$(MAKE) --directory=$@
-
-examples: $(EXAMPLE_DIRS)
 	$(Q)true
 
 install: lib
@@ -87,22 +81,49 @@ install: lib
 	$(Q)$(INSTALL) -m 0644 lib/*.ld $(LIBDIR)
 	$(Q)$(INSTALL) -m 0644 lib/efm32/*/*.ld $(LIBDIR)
 	@printf "  INSTALL scripts\n"
-	$(Q)$(INSTALL) -m 0644 scripts/* $(SHAREDIR)
+	$(Q)$(INSTALL) -m 0644 scripts/*.scr $(SHAREDIR)
 
-doc:
+
+html doc:
 	$(Q)$(MAKE) -C doc html
 
-# Bleh http://www.makelinux.net/make3/make3-CHP-6-SECT-1#make3-CHP-6-SECT-1
-clean: cleanheaders
-	$(Q)for i in $(LIB_DIRS) \
-		     $(EXAMPLE_DIRS); do \
-		if [ -d $$i ]; then \
-			printf "  CLEAN   $$i\n"; \
-			$(MAKE) -C $$i clean SRCLIBDIR=$(SRCLIBDIR) || exit $?; \
+clean: $(IRQ_DEFN_FILES:=.cleanhdr) $(LIB_DIRS:=.clean) $(EXAMPLE_DIRS:=.clean) doc.clean styleclean
+
+%.clean:
+	$(Q)if [ -d $* ]; then \
+		printf "  CLEAN   $*\n"; \
+		$(MAKE) -C $* clean SRCLIBDIR=$(SRCLIBDIR) || exit $?; \
+	fi;
+
+
+stylecheck: $(STYLECHECKFILES:=.stylecheck)
+styleclean: $(STYLECHECKFILES:=.styleclean)
+
+# the cat is due to multithreaded nature - we like to have consistent chunks of text on the output
+%.stylecheck: %
+	$(Q)if ! grep -q "* It was generated by the irq2nvic_h script." $* ; then \
+		$(STYLECHECK) $(STYLECHECKFLAGS) $* > $*.stylecheck; \
+		if [ -s $*.stylecheck ]; then \
+			cat $*.stylecheck; \
+		else \
+			rm -f $*.stylecheck; \
 		fi; \
-	done
-	@printf "  CLEAN   doxygen\n"
-	$(Q)$(MAKE) -C doc clean
+	fi;
 
-.PHONY: build lib $(LIB_DIRS) examples $(EXAMPLE_DIRS) install doc clean generatedheaders cleanheaders
+%.styleclean:
+	$(Q)rm -f $*.stylecheck;
 
+
+LDTESTS		:=$(wildcard ld/tests/*.data)
+
+genlinktests: $(LDTESTS:.data=.ldtest)
+
+%.ldtest:
+	@if ./scripts/genlinktest.sh $* >/dev/null; then\
+		printf "  TEST  OK  : $*\n";		\
+	else						\
+		printf "  TEST FAIL : $*\n";		\
+	fi;
+
+
+.PHONY: build lib $(LIB_DIRS) install doc clean generatedheaders cleanheaders stylecheck genlinktests
