Build modular protocol

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,8 +1,16 @@
+## the following disable builtin rules which we don't need
+## and make debugging harder
+MAKEFLAGS += --no-builtin-rules
+.SUFFIXES:
+
 # Use VERBOSE=1 to enable verbose make
 TYPE     ?= dev
 TARGET   ?= devo8
 PROGMODE ?= STATUS_SCREEN
 NUM_MODELS ?= 30
+
+all : $(ALL)
+
 include target/$(TARGET)/Makefile.inc
 
 ifdef CROSS
@@ -13,6 +21,7 @@ ifdef CROSS
     AS   = $(CROSS)as
     CP   = $(CROSS)objcopy
     DUMP = $(CROSS)objdump
+    NM   = $(CROSS)nm
 endif
 CC   ?= gcc
 CXX  ?= g++
@@ -22,9 +31,22 @@ AS   ?= as
 CP   ?= objcopy
 DUMP ?= objdump
 
+ODIR     = objs/$(TARGET)$(ODIREXT)
+
 SRC_C    := $(SRC_C) $(wildcard *.c) $(wildcard screen/*.c) $(wildcard screen/$(SCREENSIZE)/*.c) \
-                $(wildcard gui/*.c) $(wildcard pages/$(SCREENSIZE)/*.c) $(wildcard protocol/*.c) \
-                $(wildcard config/*.c)
+                $(wildcard gui/*.c) $(wildcard pages/$(SCREENSIZE)/*.c) $(wildcard config/*.c)
+ifdef MODULAR
+SRC_C    := $(SRC_C) protocol/protocol.c
+CFLAGS := $(CFLAGS) -DMODULAR=$(MODULAR)
+PROTO_SRC_C := $(filter-out protocol/protocol.c, $(wildcard protocol/*.c))
+PROTO_OBJS  := $(addprefix $(ODIR)/, $(notdir $(PROTO_SRC_C:.c=.o)))
+PROTO_LIBS  := $(addprefix $(ODIR)/, $(notdir $(PROTO_SRC_C:.c=.bin)))
+PROTO_EXTRA_OBJS := $(addprefix $(ODIR)/, $(notdir $(PROTO_EXTRA_C:.c=.o)))
+SYMBOL_FILE := $(ODIR)/symbolfile
+else
+SRC_C    := $(SRC_C) $(wildcard protocol/*.c)
+endif
+
 ifndef NO_STANDARD_GUI
 SRC_C    := $(SRC_C) $(wildcard pages/$(SCREENSIZE)/simple/*.c)
 endif
@@ -36,14 +58,13 @@ SRC_S    := $(SRC_S) $(wildcard *.s)
 SRC_CXX  := $(SRC_CXX) $(wildcard *.cpp)
 SRCS     := $(SRC_C) $(SRC_CXX) $(SRC_S)
 
-ODIR     = objs/$(TARGET)$(ODIREXT)
 OBJS 	 = $(addprefix $(ODIR)/, $(notdir $(SRC_C:.c=.o) $(SRC_S:.s=.o) $(SRC_CXX:.cpp=.o)))
 
 FONTS    = filesystem/devo10/media/12normal.fon \
            filesystem/devo8/media/15normal.fon \
            filesystem/devo8/media/23bold.fon
 
-MODELDIR = filesystem/models
+MODELDIR = filesystem/$(FILESYSTEM)/models
 ifeq "$(wildcard ../.hg )" ""
   HGVERSION := ${TARGET}-Unknown
 else
@@ -54,6 +75,12 @@ else
   endif
 endif
 
+# Rebuild on hg version change.
+# Based on http://mercurial.selenic.com/wiki/VersioningWithMake
+# We need to always run this code, as opposed to running it from a prerequisite
+# The HGTEST variable is not used
+HGTEST := $(shell [ -f $(ODIR)/hgstamp ] || touch $(ODIR)/hgstamp; echo $(HGVERSION) | cmp -s $(ODIR)/hgstamp - || echo $(HGVERSION) > $(ODIR)/hgstamp)
+
 ifeq "$(TYPE)" "dev"
   CFLAGS   := $(CFLAGS) -g -DBUILDTYPE_DEV
 endif
@@ -62,11 +89,11 @@ CFLAGS   := $(CFLAGS) -Wall -Wextra -I. -D$(PROGMODE) -std=gnu99 -Itarget/$(TARG
 CXXFLAGS := $(CXXFLAGS) $(patsubst -std=gnu99,,$(CFLAGS))
 EXEEXT   ?= elf
 
-LAST_MODEL := filesystem/models/model$(NUM_MODELS).ini
+LAST_MODEL := $(MODELDIR)/model$(NUM_MODELS).ini
 
-.PHONY: $(LAST_MODEL)
+ALL += $(LAST_MODEL)
 
-$(TARGET).$(EXEEXT): $(LINKFILE) $(OBJS) $(LAST_MODEL) $(LIBOPENCM3)
+$(TARGET).$(EXEEXT): $(LINKFILE) $(OBJS) $(LIBOPENCM3)
 	@echo " + Building '$@'"
 ifdef LINKFILE #Create an empty 'obj/optimize.ld' just in case the linker script needs it
 	/bin/rm -f objs/optimize.ld
@@ -77,23 +104,32 @@ ifeq ("$(SRC_CXX)", " ")
 else
 	$(CXX) -o $@ $(OBJS) $(LIBOPENCM3) $(LFLAGS) $(LFLAGS2) $(CFLAGS)
 endif
+ifdef MODULAR
+	$(NM) $@ | perl -ne 'if(! /[.\$$]/ && /^(\S+).* (\S+)$$/) {print "$$2 = 0x$$1;\n";}' > $(SYMBOL_FILE)
+endif
+
+#If any dependencies don't exist (like protocol.ld), this rule will fail with something like:
+#make: *** No rule to make target `objs/devo7e/devo.bin', needed by `Makefile'.  Stop.
+$(ODIR)/%.bin: $(ODIR)/%.o $(PROTO_LINKFILE) $(PROTO_EXTRA_OBJS) $(TARGET).$(EXEEXT)
+	@echo " + Building '$@'"
+	$(LD) -o $(@:.bin=.elf) $< $(PROTO_EXTRA_OBJS) -gc-sections -Map=$(@:.bin=.map) --cref -T$(PROTO_LINKFILE) --just-symbols=$(SYMBOL_FILE)
+	$(CP) -O binary  $(@:.bin=.elf) $@
 
 $(LAST_MODEL): model_template.ini tx_template.ini $(FONTS)
-	@echo " + Copying template files"
-	for tx in devo8 devo10; do \
-		cp -prf filesystem/common/media filesystem/$$tx/; \
-		cp -prf filesystem/common/template filesystem/$$tx/; \
-		mkdir filesystem/$$tx/language 2> /dev/null || true; \
-                ../utils/extract_strings.pl -target $$tx; \
-		cp tx_template.ini filesystem/$$tx/tx.ini; \
-		mkdir filesystem/$$tx/models 2> /dev/null || true; \
-		echo 'name=Model1' > filesystem/$$tx/models/model1.ini; \
-		cat model_template.ini >> filesystem/$$tx/models/model1.ini; \
-		cp model_template.ini filesystem/$$tx/models/default.ini; \
-		number=2 ; while [ $$number -le 30 ] ; do \
-			cp model_template.ini filesystem/$$tx/models/model$$number.ini; \
-			number=`expr $$number + 1`; \
-			done; \
+	@echo " + Copying template files for $(FILESYSTEM)"
+	export tx=$(FILESYSTEM); \
+	cp -prf filesystem/common/media filesystem/$$tx/; \
+	cp -prf filesystem/common/template filesystem/$$tx/; \
+	mkdir filesystem/$$tx/language 2> /dev/null || true; \
+               ../utils/extract_strings.pl -target $$tx; \
+	cp tx_template.ini filesystem/$$tx/tx.ini; \
+	mkdir filesystem/$$tx/models 2> /dev/null || true; \
+	echo 'name=Model1' > filesystem/$$tx/models/model1.ini; \
+	cat model_template.ini >> filesystem/$$tx/models/model1.ini; \
+	cp model_template.ini filesystem/$$tx/models/default.ini; \
+	number=2 ; while [ $$number -le 30 ] ; do \
+		cp model_template.ini filesystem/$$tx/models/model$$number.ini; \
+		number=`expr $$number + 1`; \
 		done
 
 # The following enables quiet output unless you use VERBOSE=1
@@ -136,6 +172,8 @@ filesystem/devo8/media/23bold.fon: fonts/23bold.bdf
 ## The autodependency magic below was adapeted from:
 ## http://mad-scientist.net/make/autodep.html
 -include $(OBJS:.o=.P)
+-include $(PROTO_OBJS:.o=.P)
+-include $(PROTO_EXTRA_OBJS:.o=.P)
 dollar = $$
 define define_compile_rules
 $(ODIR)/%.o: $(1)%.c
@@ -155,20 +193,15 @@ $(ODIR)/%.o: $(1)%.cpp
             rm -f $(ODIR)/$$*.d
 
 endef
-$(foreach directory,$(sort $(dir $(SRCS))),$(eval $(call define_compile_rules,$(directory))))
+$(foreach directory,$(sort $(dir $(SRCS) $(PROTO_EXTRA_C))),$(eval $(call define_compile_rules,$(directory))))
 
 # Rebuild on hg version change.
-# From http://mercurial.selenic.com/wiki/VersioningWithMake
 $(ODIR)/version.o: $(ODIR)/hgstamp
-.PHONY: $(ODIR)/hgstamp
-$(ODIR)/hgstamp:
-	[ -f $@ ] || touch $@
-	echo $(HGVERSION) | cmp -s $@ - || echo $(HGVERSION) > $@
 
 # phony targets
 .PHONY: clean
 # recompile if the Makefile changes
-$(OBJS): Makefile target/$(TARGET)/Makefile.inc $(EXTRA_MAKEFILES)
+$(OBJS) $(PROTO_OBJS) ($PROTO_EXTRA_OBJS): target/$(TARGET)/Makefile.inc $(EXTRA_MAKEFILES)
 
 zip: $(TARGET).dfu
 	mv -f $(TARGET).dfu deviation-$(HGVERSION).dfu
@@ -187,3 +220,7 @@ release:
 	make TARGET=devo8 fs
 	make TARGET=devo10 fs
 	#make TARGET=emu_devo8 TYPE=prd WINDOWS=1 
+
+#The following forces re-reading the Makefile so that the 'all' prerequisites can be defined
+#after the definition of the 'all' rule
+Makefile: $(ALL)
